#!/usr/bin/env bash

output_file=""
while getopts ":o:" opt; do
    case $opt in
        o)
            output_file=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

shift $(expr $OPTIND - 1 )

if [ -z $output_file ]
then
    echo "Must specify output file using the -o flag"
    exit 1
fi

sample_tally=0
line_tally=0
for filename in "$@"
do
    {
        echo "$filename"
        # Skip header
        while : ; do
            read -r line
            [[ ${line::1} == '%' ]] || break
        done
        # Save the 2nd dimension, since it is the only unchanged one
        transcripts="$(cut -f2 <(echo "$line"))"

        local_sample=0
        while read -r sample transcript quant
        do
            if [ "$sample" -gt "$local_sample" ]
            then
                sample_tally=$((sample_tally+$sample-$local_sample))
                local_sample=$sample
            fi
            echo "$sample_tally	$transcript	$quant" >> $output_file
            line_tally=$((line_tally+1))
        done
    } < "$filename"
done

# Prepend header and matrix dimensions
sed -i "1s;^;%%MatrixMarket matrix coordinate real general\n$sample_tally\t$transcripts\t$line_tally\n;" $output_file
